### ISSUE TITLE
Deadlock when using Monix Queue

### ISSUE THREAD

**Issue by dmgcodevil** [parapet-io/parapet#7]
Application freezes when using Monix Queue. Thread dump:

```scala 
"ScalaTest-run-running-SelfSendSpec" #1 prio=5 os_prio=0 tid=0x0000000002a85800 nid=0x58ec waiting on condition [0x000000000290c000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000005c3003258> (a cats.effect.internals.IOPlatform$OneShotLatch)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at cats.effect.internals.IOPlatform$.$anonfun$unsafeResync$2(IOPlatform.scala:50)
	at cats.effect.internals.IOPlatform$$$Lambda$190/41031373.apply$mcV$sp(Unknown Source)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.package$.blocking(package.scala:142)
	at cats.effect.internals.IOPlatform$.unsafeResync(IOPlatform.scala:50)
	at cats.effect.IO.unsafeRunTimed(IO.scala:325)
	at cats.effect.IO.unsafeRunSync(IO.scala:240)

```

**Comment by dmgcodevil** [comment]
fixed
